set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME . "/vim"
call mkdir($XDG_DATA_HOME . "/vim/spell", "p")

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir($XDG_STATE_HOME . "/vim/backup", "p")
set directory=$XDG_STATE_HOME/vim/swap | call mkdir($XDG_STATE_HOME . "/vim/swap", "p")
set undodir=$XDG_STATE_HOME/vim/undo | call mkdir($XDG_STATE_HOME . "/vim/undo", "p")
set viewdir=$XDG_STATE_HOME/vim/view | call mkdir($XDG_STATE_HOME . "/vim/view", "p")

if !has('nvim')
  set viminfofile=$XDG_STATE_HOME/vim/viminfo
endif
