[Unit]
Description=Calibre Server Service
Wants=network-online.target
After=network-online.target

[Service]
User=calibre
Group=calibre
ExecStart=
ExecStart=/usr/bin/calibre-server --port 8080 --url-prefix /calibre --enable-auth --userdb /srv/calibre/users.sqlite --access-log /srv/calibre/access.log --auth-mode basic /srv/calibre/
Type=simple

[Install]
WantedBy=multi-user.target
