server {
    listen 443 ssl;
    http2 on;
    listen [::]:443 ssl;
    more_clear_headers Server;
    server_name sftp.archnet.lol;

    ssl_certificate /etc/ssl/certs/sftp.archnet.lol-origin.pem;
    ssl_certificate_key /etc/ssl/private/sftp.archnet.lol-origin.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    include /etc/nginx/snippets/security-headers.conf;

    location / {
        return 301 https://aslan.archnet.lol/sftp-viewer/;
    }

    error_page 400 /error/400.html;
    error_page 404 /error/404.html;
    error_page 500 /error/500.html;
    error_page 502 /error/502.html;
    error_page 503 /error/503.html;
    error_page 504 /error/504.html;
    location ^~ /error/ {
        root /www/data;
        internal;
    }
}
