#!/bin/sh
# shellcheck disable=all

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
userprofile=$HOME/.config/X11/xprofile
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
sysprofile=/etc/xprofile

# merge in defaults and keymaps

[ -f "$sysresources" ] && xrdb -merge $sysresources
[ -f "$sysmodmap" ] && xmodmap $sysmodmap
[ -f "$sysprofile" ] && . "$sysprofile"
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"
[ -f "$userprofile" ] && . "$userprofile"
# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xsetroot -solid "#1e1e2e"
xsetroot -cursor_name left_ptr
exec qtile start
# exec i3
# exec qtile start -c /usr/lib/python3.11/site-packages/libqtile/resources/default_config.py
