export ZDOTDIR=$HOME/.config/zsh
# XDG Base Directory specification
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export MATLAB_LOG_DIR="$XDG_CACHE_HOME/matlab"
# export MATLAB_SHELL="/bin/zsh --aliases /etc/zsh/matlab_aliases.zsh"
